{% set name = "trianglesolver" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trianglesolver-{{ version }}.tar.gz
  sha256: 4af18aade579d5c0d64389b3e65aeaf06cff26319762ccd859e3268559a76aea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5

test:
  imports:
    - trianglesolver
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/trianglesolver
  summary: Find all the sides and angles of a triangle, if you know some of the sides and/or angles. (Uses the Law of Sines and Law of Cosines.)
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/sbyrnes321/trianglesolver

extra:
  recipe-maintainers:
    - ndevenish
